version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
  redis:
    image: "redis:alpine"